"""
Test game: FULL AI — all LLM-powered agents.

Launches 6 Gemini-powered LLM agents and lets them battle it out.
This is the ultimate stress test for the validation/adaptation layer,
since every bot is operating with 2-5s latency.

Watch for:
  - Adapted action counts (how many LLM actions were adjusted to reality)
  - Fallback action counts (how many ticks used emergency rules while LLM thought)
  - Stamina gate counts (LLM tried to act without enough stamina)
  - AFK saves (near-wolf-kill prevented by forced displacement)

Prerequisites:
    1. Start the game server:
           cd server
           set DEV_SKIP_PAYMENT=true
           node index.js

    2. Set your Gemini API key:
           set GOOGLE_AI_API_KEY=your-key-here

    3. Run this script:
           cd sdk
           python -m scripts.test_ai_game

Environment Variables:
    GOOGLE_AI_API_KEY  — Required
    SERVER_URL         — Game server URL (default: http://localhost:3001)
    LLM_MODEL          — Gemini model to use (default: gemini-2.5-flash)
    BOT_COUNT          — Number of AI bots (default: 6, min: 3)
"""

import logging
import os
import random
import secrets
import sys
import threading
import time

from dotenv import load_dotenv

load_dotenv()

from survival_sdk import SurvivalAgent
from survival_sdk.strategies.llm import LLMStrategy, create_gemini_backend

# ── Configuration ──
SERVER = os.getenv("SERVER_URL", "http://localhost:3001")
LLM_MODEL = os.getenv("LLM_MODEL", "gemini-2.5-flash")
BOT_COUNT = max(3, int(os.getenv("BOT_COUNT", "6")))

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(name)s] %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger("test_ai")

# Track all strategies for final stats
all_strategies: list[tuple[str, LLMStrategy]] = []
stats_lock = threading.Lock()


def generate_dummy_key():
    return "0x" + secrets.token_hex(32)


def run_bot(index: int, strategy: LLMStrategy):
    """Run a single LLM bot in its own thread."""
    key = generate_dummy_key()
    label = f"AI-{index}"
    try:
        agent = SurvivalAgent(SERVER, key)
        agent.join(spawn_preference=[
            random.randint(5, 45),
            random.randint(5, 45),
        ])
        logger.info(f"Bot {index} ({label}) joined as '{agent.display_name}'")
        agent.run(strategy)
        logger.info(f"Bot {index} ({label}) finished.")
    except Exception as e:
        logger.error(f"Bot {index} ({label}) error: {e}")


def print_final_stats():
    """Print a summary table of all bots' validation stats."""
    print()
    print("═" * 72)
    print("  VALIDATION LAYER STATS")
    print("═" * 72)
    print(
        f"  {'Bot':<8} {'LLM':>5} {'Adapt':>6} {'Fall':>6} "
        f"{'Stale':>6} {'Inval':>6} {'Stam':>6} {'AFK':>5}"
    )
    print("  " + "─" * 62)

    totals = [0] * 7
    for label, s in all_strategies:
        row = [
            s._total_llm_actions,
            s._total_adapted_actions,
            s._total_fallback_actions,
            s._total_stale_discards,
            s._total_invalid_discards,
            s._total_stamina_gates,
            s._total_afk_saves,
        ]
        for i in range(7):
            totals[i] += row[i]
        print(
            f"  {label:<8} {row[0]:>5} {row[1]:>6} {row[2]:>6} "
            f"{row[3]:>6} {row[4]:>6} {row[5]:>6} {row[6]:>5}"
        )

    print("  " + "─" * 62)
    print(
        f"  {'TOTAL':<8} {totals[0]:>5} {totals[1]:>6} {totals[2]:>6} "
        f"{totals[3]:>6} {totals[4]:>6} {totals[5]:>6} {totals[6]:>5}"
    )
    print()
    print("  Legend:")
    print("    LLM   = Actions generated by the LLM and executed")
    print("    Adapt = LLM actions that were adapted to current state")
    print("    Fall  = Ticks where fallback rules acted (LLM was thinking)")
    print("    Stale = LLM responses discarded as too old")
    print("    Inval = LLM actions fully invalidated (unfulfillable)")
    print("    Stam  = Actions blocked by insufficient stamina")
    print("    AFK   = Forced moves to prevent wolf-kill (AFK detection)")
    print("═" * 72)
    print()


def main():
    # Verify API key
    api_key = os.getenv("GOOGLE_AI_API_KEY") or os.getenv("GEMINI_API_KEY")
    if not api_key:
        print("\n  ✗ GOOGLE_AI_API_KEY not set!")
        print("    Set it: set GOOGLE_AI_API_KEY=your-key-here")
        print("    Or create a .env file in the sdk/ directory.\n")
        sys.exit(1)

    print()
    print("═" * 50)
    print("  Protocol: SURVIVAL — Full AI Game Test")
    print(f"  Server: {SERVER}")
    print(f"  Model:  {LLM_MODEL}")
    print(f"  Bots:   {BOT_COUNT}x LLM (all Gemini)")
    print("═" * 50)
    print()

    backend = create_gemini_backend(model=LLM_MODEL)

    threads = []
    for i in range(BOT_COUNT):
        # Each bot gets its own LLMStrategy instance (own state/thread)
        strategy = LLMStrategy(backend=backend)
        label = f"AI-{i}"
        all_strategies.append((label, strategy))

        t = threading.Thread(
            target=run_bot, args=(i, strategy), daemon=True
        )
        threads.append(t)
        print(f"  Launching bot {i}: [{label}]")
        t.start()
        time.sleep(0.5)

    print(f"\n  All {len(threads)} bots launched. Waiting for game...\n")

    try:
        for t in threads:
            t.join()
    except KeyboardInterrupt:
        print("\n  Interrupted.")

    print_final_stats()
    print("  Game complete!")


if __name__ == "__main__":
    main()
